image: node:8

pipelines:
  default:
    - step:
        script:
          - docker version
          - npm install
          - docker build -t kylecordes/abc-in-class-server .
          - echo docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          - echo docker push kylecordes/abc-in-class-server
        services:
          - docker

options:
  docker: true
